#' Write worklist to file
#'
#' writes worklist to file, filename defined in \code{init}.
#' @param gwl object of class gwl
#' @param lineNumbers logical, should linenumbers be prepended to existing comments? Defaults to \code{FALSE}
#' @param print logical, should the worklist be printed in R? Defaults to \code{FALSE}
#' @param saveWT logical, should the worktable be saved as a \code{txt} file?
#' @family general methods
#' @export
write.gwl <- function(gwl,
  print = FALSE,
  lineNumbers = TRUE,
  saveWT = FALSE,
  quietly = FALSE){
  #add linenumbers
  if (lineNumbers){
      selectComments <- !is.na(str_match(gwl$worklist$command, "Comment"))
      lineN <- gwl$worklist$line[selectComments]
      maxLineN <- max(gwl$worklist$line)
      gwl$worklist$command[selectComments] <- str_replace(
        gwl$worklist$command[selectComments],
        fixed("B;Comment(\""),
        str_c("B;Comment(\"", lineN, "/", maxLineN, " | "))
  }
  if (saveWT){
      write_tsv(gwl$worktable,
        str_c(gwl$defaults$filename, "_worktable.txt"))
      cat(paste0("worktable saved as ",
        paste0(gwl$defaults$filename,
        "_worktable.txt")), "\n")
  }

  write(gwl$worklist$command,
    str_c(gwl$defaults$filename, ".gwl"),
    sep = "")

  if (print){
    print(gwl)
  }
  if (!quietly){
    cat("worklist saved as", str_c(gwl$defaults$filename, ".gwl"), "\n")
    cat("Check worktable layout!", "\n")
  }
}

#' add to worktable
#'
#' adds the labware to a worktable file to keep track of used labware
#' @param RackLabel Max. 32 characters User-defined label (name) which is
#'      assigned to the labware.
#' @param grid integer 1 - 67 labware location - carrier grid position
#' @param site integer 0 - 127 labware location - (site on carrier - 1)
#' @param RackType Max. 32 characters, Labware type (configuration name),
#'      e.g. “384 Well, landscape”. Only used for basic worklists.
#' @param Volume needed in Rack: this will be filled up by the functions
#' @param LiquidClass class in the Rack.
#' @return a string with warnings generated by the function
#' @family general methods
#' @export
addToWorktable <- function(RackLabel = "",
  grid = 0,
  site = 0,
  RackType = "",
  Volume = 0,
  LiquidClass = ""){

  worktable <- gwl$worktable
  labware_add <- data.frame(
    RackLabel = RackLabel,
    grid = grid,
    site = site,
    RackType = RackType,
    Volume = Volume,
    LiquidClass = LiquidClass)

  for (i in 1:dim(labware_add)[1]){
    RackLabel_defined <- dim(
      subset(worktable, RackLabel == labware_add$RackLabel[i]))[1]

    if (RackLabel_defined == 1){
      stop("RackLabel already defined")
    } else {
      gridSiteCheck <-
        worktable[worktable$grid == grid & worktable$site == site, ]
      if (dim(gridSiteCheck)[1] == 1){
        stop(paste0("Grid/Site allready occupied by ", gridSiteCheck$RackLabel))
      }
      worktable <- rbind(worktable, labware_add[i, ])
    }
  }

  gwl$worktable <<- worktable
}

#' add to worklist
#'
#' adds a command to the worklist
#' @param command character, or vector of characters. ” must be escaped (\")
#' @param mode one of "basic", "advanced", specifying wheter it is a basic or an
#'      advanced worklist command.
#' @param CMadd_warning passed to the worklist, Info only.
#' @family general methods
#' @export
addToWorklist <- function(command, mode, CMadd_warning = ""){
  all_warning <- str_c(CMadd_warning, sep = "|")
  last_line <- tail(gwl$worklist, 1)$line
  command_add <- data.frame(
    line = seq_along(command) + last_line,
    command = command,
    mode = mode,
    warning = all_warning)
  gwl$worklist <<- rbind(gwl$worklist, command_add)
}
